#!/bin/bash
args=("$@")
if [ "$#" -eq  "0" ]
   then
     /usr/bin/php /home/immortal/Work/Webbamboo/commander/bin/console commander:helper
 else
     /usr/bin/php /home/immortal/Work/Webbamboo/commander/bin/console ${args[0]} ${args[1]} ${args[2]}
 fi
